/**
 * Fix vocabulary meanings that are still in English.
 * Strategy: Use a comprehensive English→Indonesian translation map
 * for all WaniKani-style vocabulary meanings.
 */
const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

const envContent = fs.readFileSync(path.join(__dirname, '..', '.env.local'), 'utf8');
const env = {};
envContent.split('\n').forEach(line => { 
  const p = line.split('='); 
  if (p.length >= 2) env[p[0].trim()] = p.slice(1).join('=').trim(); 
});
const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

// Comprehensive English → Indonesian translation map for WaniKani vocabulary meanings
const VOCAB_TRANSLATIONS = {
  'About': 'Tentang',
  'Abroad': 'Luar Negeri',
  'Abruptly': 'Tiba-tiba',
  'Action': 'Tindakan',
  'Activity': 'Aktivitas',
  'Admirable': 'Mengagumkan',
  'Admission': 'Penerimaan',
  'Admission Exam': 'Ujian Masuk',
  'Admission Examination': 'Ujian Penerimaan',
  'Admission Test': 'Ujian Masuk',
  'Admission To A Hospital': 'Rawat Inap',
  'After': 'Setelah',
  'Always Open': 'Selalu Buka',
  'Ancient': 'Kuno',
  'Another': 'Lainnya',
  'Another Thing': 'Hal Lain',
  'Anticipation': 'Antisipasi',
  'Anxiety': 'Kecemasan',
  'Application': 'Lamaran',
  'Aqua Blue': 'Biru Muda',
  'Aqua Blue Color': 'Warna Biru Muda',
  'Aqueduct': 'Saluran Air',
  'Archaeology': 'Arkeologi',
  'Arrangements': 'Pengaturan',
  'Arriving At The Office': 'Tiba di Kantor',
  'As For Me': 'Mengenai Saya',
  'As Hard As One Can': 'Sekuat Tenaga',
  'Assembly': 'Pertemuan',
  'Atmosphere': 'Suasana',
  'Attention': 'Perhatian',
  'Baby Cow': 'Anak Sapi',
  'Backstreets': 'Gang Belakang',
  'Bad At': 'Tidak Bisa',
  'Bad Guy': 'Orang Jahat',
  'Bad Mouth': 'Mulut Kotor',
  'Bad Woman': 'Wanita Jahat',
  'Bargain Sale': 'Diskon Besar',
  'Basement': 'Ruang Bawah Tanah',
  'Bathing Suit': 'Baju Renang',
  'Batter': 'Pemukul',
  'Beautiful': 'Cantik/Indah',
  'Before': 'Sebelum',
  'Beginning': 'Awal',
  'Behavior': 'Perilaku',
  'Behaviour': 'Perilaku',
  'Below': 'Di Bawah',
  'Best Friend': 'Sahabat',
  'Bike': 'Sepeda',
  'Bill': 'Tagihan',
  'Bills': 'Tagihan',
  'Black People': 'Orang Berkulit Hitam',
  'Bookshop': 'Toko Buku',
  'Break': 'Istirahat',
  'Brown Color': 'Warna Coklat',
  'Bull': 'Banteng',
  'Business': 'Bisnis',
  'Cadaver': 'Mayat',
  'Cancellation': 'Pembatalan',
  'Capital Letters': 'Huruf Kapital',
  'Card': 'Kartu',
  'Carnivore': 'Karnivora',
  'Carry Out': 'Melaksanakan',
  'Celebrate': 'Merayakan',
  'Celebration': 'Perayaan',
  'Chairman': 'Ketua',
  'Change': 'Perubahan',
  'Cherry Blossom': 'Bunga Sakura',
  'Chinese Character': 'Karakter Cina',
  'Chinese Characters': 'Karakter Cina',
  'Chopsticks': 'Sumpit',
  'Citizen': 'Warga Negara',
  'City Hall': 'Balai Kota',
  'Class': 'Kelas',
  'Climate': 'Iklim',
  'Club Activities': 'Kegiatan Klub',
  'Collection': 'Koleksi',
  'College Student': 'Mahasiswa',
  'Colored': 'Berwarna',
  'Comfort': 'Kenyamanan',
  'Commercial': 'Komersial',
  'Communication': 'Komunikasi',
  'Company Employee': 'Karyawan',
  'Comparison': 'Perbandingan',
  'Competition': 'Kompetisi',
  'Concept': 'Konsep',
  'Condition': 'Kondisi',
  'Congratulations': 'Selamat',
  'Conversation': 'Percakapan',
  'Cooking': 'Memasak',
  'Copy': 'Salinan',
  'Corpse': 'Jenazah',
  'Country': 'Negara',
  'Cultural': 'Budaya',
  'Culture': 'Kebudayaan',
  'Customer': 'Pelanggan',
  'Cute': 'Imut/Lucu',
  'Daily': 'Harian',
  'Dark': 'Gelap',
  'Day After Tomorrow': 'Lusa',
  'Day Before Yesterday': 'Kemarin Lusa',
  'Deadline': 'Batas Waktu',
  'Death': 'Kematian',
  'Degree': 'Gelar',
  'Delivery': 'Pengiriman',
  'Democracy': 'Demokrasi',
  'Departing': 'Berangkat',
  'Departure': 'Keberangkatan',
  'Design': 'Desain',
  'Desire': 'Keinginan',
  'Difficult': 'Sulit',
  'Direction': 'Arah',
  'Distance': 'Jarak',
  'Doctor': 'Dokter',
  'Doesn\'t Understand': 'Tidak Mengerti',
  'Double': 'Ganda',
  'Draft': 'Konsep',
  'Dress Code': 'Kode Berpakaian',
  'Dry': 'Kering',
  'Each Month': 'Setiap Bulan',
  'Each Week': 'Setiap Minggu',
  'Each Year': 'Setiap Tahun',
  'Early Morning': 'Pagi Buta',
  'Economics': 'Ekonomi',
  'Economy': 'Ekonomi',
  'Education': 'Pendidikan',
  'Effort': 'Usaha',
  'Election': 'Pemilihan',
  'Electricity': 'Listrik',
  'Elementary School': 'Sekolah Dasar',
  'Elevator': 'Lift',
  'Employee': 'Karyawan',
  'Encounter': 'Pertemuan',
  'End': 'Akhir',
  'Energy': 'Energi',
  'Entrance': 'Pintu Masuk',
  'Error': 'Kesalahan',
  'Especially': 'Terutama',
  'Exactly': 'Tepat',
  'Examination': 'Ujian',
  'Exchange': 'Pertukaran',
  'Experience': 'Pengalaman',
  'Experiment': 'Eksperimen',
  'Explanation': 'Penjelasan',
  'Express Train': 'Kereta Ekspres',
  'Extension': 'Perpanjangan',
  'Extra Large': 'Sangat Besar',
  'Facts': 'Fakta',
  'Failure': 'Kegagalan',
  'Fall And Fail': 'Jatuh dan Gagal',
  'Fall Down': 'Jatuh',
  'Famous': 'Terkenal',
  'Fear': 'Ketakutan',
  'Feelings': 'Perasaan',
  'Festival': 'Festival',
  'Field': 'Lapangan',
  'Fight': 'Bertarung',
  'Film': 'Film',
  'First': 'Pertama',
  'Fish Market': 'Pasar Ikan',
  'Flat': 'Datar',
  'Flower': 'Bunga',
  'Fluffy': 'Berbulu Halus',
  'Foreign': 'Asing',
  'Forest': 'Hutan',
  'Form': 'Formulir',
  'Free': 'Gratis',
  'Fresh': 'Segar',
  'Friend': 'Teman',
  'From Now On': 'Mulai Sekarang',
  'Front': 'Depan',
  'Function': 'Fungsi',
  'General': 'Umum',
  'Get Sick': 'Sakit',
  'Gift': 'Hadiah',
  'Glasses': 'Kacamata',
  'Goal': 'Tujuan',
  'Good': 'Baik',
  'Good At': 'Pandai dalam',
  'Good Friend': 'Teman Baik',
  'Good Health': 'Kesehatan Baik',
  'Good Luck': 'Semoga Berhasil',
  'Government': 'Pemerintah',
  'Gradually': 'Secara Bertahap',
  'Grandchild': 'Cucu',
  'Grandmother': 'Nenek',
  'Grave': 'Kuburan',
  'Great': 'Besar/Hebat',
  'Group': 'Kelompok',
  'Harmony': 'Harmoni',
  'Headquarters': 'Kantor Pusat',
  'Health': 'Kesehatan',
  'Heart': 'Hati',
  'Help': 'Bantuan',
  'Herbivore': 'Herbivora',
  'High School': 'SMA',
  'High School Student': 'Siswa SMA',
  'History': 'Sejarah',
  'Holiday': 'Hari Libur',
  'Home': 'Rumah',
  'Homework': 'Pekerjaan Rumah',
  'Honest': 'Jujur',
  'Hospital': 'Rumah Sakit',
  'How Many Days': 'Berapa Hari',
  'How Many Times': 'Berapa Kali',
  'Human': 'Manusia',
  'Human Body': 'Tubuh Manusia',
  'Hundred Yen': 'Seratus Yen',
  'I See': 'Begitu',
  'Idea': 'Ide',
  'Important': 'Penting',
  'Impossible': 'Tidak Mungkin',
  'In A Hurry': 'Terburu-buru',
  'In Front Of': 'Di Depan',
  'In Total': 'Secara Keseluruhan',
  'Inability': 'Ketidakmampuan',
  'Incident': 'Kejadian',
  'Indeed': 'Memang',
  'Industry': 'Industri',
  'Information': 'Informasi',
  'Inside': 'Di Dalam',
  'Interest': 'Minat',
  'Intermediate': 'Menengah',
  'Introduction': 'Perkenalan',
  'Invention': 'Penemuan',
  'Invitation': 'Undangan',
  'Japanese Food': 'Makanan Jepang',
  'Job': 'Pekerjaan',
  'Joint': 'Bersama',
  'Kind': 'Baik Hati',
  'Kitchen': 'Dapur',
  'Knowledge': 'Pengetahuan',
  'Language': 'Bahasa',
  'Large': 'Besar',
  'Last Month': 'Bulan Lalu',
  'Last Week': 'Minggu Lalu',
  'Last Year': 'Tahun Lalu',
  'Lawyer': 'Pengacara',
  'Learning': 'Pembelajaran',
  'Left Side': 'Sisi Kiri',
  'Letter': 'Surat',
  'Level': 'Tingkat',
  'Library': 'Perpustakaan',
  'Line': 'Garis',
  'Little': 'Sedikit',
  'Live': 'Hidup',
  'Loan': 'Pinjaman',
  'Local': 'Lokal',
  'Location': 'Lokasi',
  'Logic': 'Logika',
  'Loss': 'Kerugian',
  'Love': 'Cinta',
  'Low': 'Rendah',
  'Map': 'Peta',
  'Master': 'Master',
  'Match': 'Pertandingan',
  'Meadow': 'Padang Rumput',
  'Medical Doctor': 'Dokter',
  'Medium': 'Sedang',
  'Memory': 'Memori',
  'Message': 'Pesan',
  'Middle School': 'SMP',
  'Modern': 'Modern',
  'Money': 'Uang',
  'Months Ago': 'Beberapa Bulan Lalu',
  'Mountain Climbing': 'Mendaki Gunung',
  'Move': 'Pindah',
  'Movie': 'Film',
  'Movie Theater': 'Bioskop',
  'Music': 'Musik',
  'My House': 'Rumah Saya',
  'Mystery': 'Misteri',
  'Name Card': 'Kartu Nama',
  'Nature': 'Alam',
  'New Year': 'Tahun Baru',
  'Next Month': 'Bulan Depan',
  'Next Week': 'Minggu Depan',
  'Next Year': 'Tahun Depan',
  'Night': 'Malam',
  'None': 'Tidak Ada',
  'Noon': 'Tengah Hari',
  'Not Yet': 'Belum',
  'Now': 'Sekarang',
  'Number': 'Nomor',
  'Nurse': 'Perawat',
  'Object': 'Objek',
  'Occupation': 'Pekerjaan',
  'On Time': 'Tepat Waktu',
  'Open': 'Buka',
  'Opinion': 'Pendapat',
  'Oral': 'Lisan',
  'Order': 'Pesanan',
  'Organization': 'Organisasi',
  'Outside': 'Di Luar',
  'Overseas': 'Luar Negeri',
  'Overtime': 'Lembur',
  'Overseas Study': 'Belajar di Luar Negeri',
  'Pain': 'Rasa Sakit',
  'Parking': 'Parkir',
  'Participation': 'Partisipasi',
  'Party': 'Pesta',
  'Peace': 'Perdamaian',
  'Performance': 'Pertunjukan',
  'Permission': 'Izin',
  'Person In Charge': 'Penanggung Jawab',
  'Plan': 'Rencana',
  'Police': 'Polisi',
  'Police Officer': 'Polisi',
  'Policy': 'Kebijakan',
  'Political Party': 'Partai Politik',
  'Politics': 'Politik',
  'Post Office': 'Kantor Pos',
  'Pound': 'Pon',
  'Practice': 'Latihan',
  'Preparation': 'Persiapan',
  'Preview': 'Pratinjau',
  'Price': 'Harga',
  'Professor': 'Profesor',
  'Progress': 'Kemajuan',
  'Project': 'Proyek',
  'Proper': 'Pantas',
  'Public': 'Publik',
  'Rabbit': 'Kelinci',
  'Rain': 'Hujan',
  'Reason': 'Alasan',
  'Recording': 'Rekaman',
  'Recreation': 'Rekreasi',
  'Relationship': 'Hubungan',
  'Religion': 'Agama',
  'Rent': 'Sewa',
  'Report': 'Laporan',
  'Research': 'Penelitian',
  'Restaurant': 'Restoran',
  'Result': 'Hasil',
  'Rice Field': 'Sawah',
  'Right Side': 'Sisi Kanan',
  'River': 'Sungai',
  'Road': 'Jalan',
  'Role': 'Peran',
  'Room': 'Ruangan',
  'Rule': 'Aturan',
  'Safe': 'Aman',
  'Safety': 'Keamanan',
  'Salary': 'Gaji',
  'Same': 'Sama',
  'Sample': 'Sampel',
  'Scenery': 'Pemandangan',
  'Schedule': 'Jadwal',
  'School': 'Sekolah',
  'Season': 'Musim',
  'Section': 'Bagian',
  'Self Introduction': 'Perkenalan Diri',
  'Senior': 'Senior',
  'Service': 'Layanan',
  'Sharp': 'Tajam',
  'Short': 'Pendek',
  'Shrine': 'Kuil',
  'Sign': 'Tanda',
  'Since': 'Sejak',
  'Sleeping': 'Tidur',
  'Slowly': 'Perlahan',
  'Small': 'Kecil',
  'Society': 'Masyarakat',
  'Something': 'Sesuatu',
  'Song': 'Lagu',
  'Sorry': 'Maaf',
  'Soul': 'Jiwa',
  'Sound': 'Suara',
  'Speech': 'Pidato',
  'Speed': 'Kecepatan',
  'Sport': 'Olahraga',
  'Spring': 'Musim Semi',
  'Square': 'Kotak',
  'Stand Up': 'Berdiri',
  'Station': 'Stasiun',
  'Story': 'Cerita',
  'Strange': 'Aneh',
  'Street': 'Jalan',
  'Strong': 'Kuat',
  'Student': 'Siswa/Mahasiswa',
  'Study': 'Belajar',
  'Study Room': 'Ruang Belajar',
  'Subject': 'Mata Pelajaran',
  'Success': 'Kesuksesan',
  'Suffer': 'Menderita',
  'Summer': 'Musim Panas',
  'Supermarket': 'Supermarket',
  'Supply': 'Pasokan',
  'Support': 'Dukungan',
  'Surplus': 'Surplus',
  'Surprising': 'Mengejutkan',
  'Swimming': 'Berenang',
  'System': 'Sistem',
  'Table': 'Meja',
  'Take A Walk': 'Berjalan-jalan',
  'Tall': 'Tinggi',
  'Teacher': 'Guru',
  'Technology': 'Teknologi',
  'Temperature': 'Suhu',
  'Temple': 'Kuil',
  'Test': 'Ujian/Tes',
  'Thank You': 'Terima Kasih',
  'That': 'Itu',
  'That Person': 'Orang Itu',
  'The Other Day': 'Hari Lain',
  'The Other Side': 'Sisi Lain',
  'Think': 'Berpikir',
  'This Month': 'Bulan Ini',
  'This Person': 'Orang Ini',
  'This Week': 'Minggu Ini',
  'This Year': 'Tahun Ini',
  'Thought': 'Pemikiran',
  'Thousand': 'Seribu',
  'Time': 'Waktu',
  'Today': 'Hari Ini',
  'Together': 'Bersama',
  'Tomorrow': 'Besok',
  'Too Much': 'Terlalu Banyak',
  'Topic': 'Topik',
  'Town': 'Kota',
  'Train': 'Kereta',
  'Translation': 'Terjemahan',
  'Transportation': 'Transportasi',
  'Trip': 'Perjalanan',
  'Truth': 'Kebenaran',
  'Two People': 'Dua Orang',
  'Umbrella': 'Payung',
  'Understanding': 'Pemahaman',
  'Unexpected': 'Tidak Terduga',
  'Unit': 'Unit',
  'University': 'Universitas',
  'Unknown': 'Tidak Diketahui',
  'Unusual': 'Tidak Biasa',
  'Upset': 'Kecewa',
  'Use': 'Gunakan',
  'Vacation': 'Liburan',
  'Various': 'Berbagai',
  'Very': 'Sangat',
  'Village': 'Desa',
  'Visit': 'Kunjungi',
  'Volunteer': 'Sukarelawan',
  'Walking': 'Berjalan',
  'Want': 'Inginkan',
  'Watch': 'Tonton',
  'Water': 'Air',
  'Weather': 'Cuaca',
  'Weak': 'Lemah',
  'Welcome': 'Selamat Datang',
  'Well': 'Dengan baik',
  'Western Style': 'Gaya Barat',
  'What': 'Apa',
  'What Day': 'Hari Apa',
  'When': 'Kapan',
  'Where': 'Di mana',
  'Whisper': 'Berbisik',
  'Win': 'Menang',
  'Winter': 'Musim Dingin',
  'Worry': 'Khawatir',
  'Worst': 'Terburuk',
  'Writer': 'Penulis',
  'Yesterday': 'Kemarin',
  'Young': 'Muda',
  'Zero': 'Nol',
};

async function fixVocabMeanings() {
  console.log('Fetching all vocabulary meanings...');
  
  // Fetch all meanings from vocabulary items
  const { data: meanings, error } = await supabase
    .from('item_meanings')
    .select('id, meaning, item_id, items!inner(type, character)')
    .eq('items.type', 'vocabulary');
  
  if (error) { console.error('Error fetching meanings:', error); return; }
  
  console.log(`Total vocabulary meanings: ${meanings.length}`);
  
  let updates = 0;
  let deletes = 0;
  let skipped = 0;
  
  // Process each meaning
  for (const row of meanings) {
    const origMeaning = row.meaning;
    const translation = VOCAB_TRANSLATIONS[origMeaning];
    
    if (!translation) {
      skipped++;
      continue;
    }
    
    // Check if translated version already exists for this item
    const { data: existing } = await supabase
      .from('item_meanings')
      .select('id')
      .eq('item_id', row.item_id)
      .eq('meaning', translation)
      .neq('id', row.id);
    
    if (existing && existing.length > 0) {
      // Already have translated version, delete the English
      await supabase.from('item_meanings').delete().eq('id', row.id);
      deletes++;
    } else {
      // Update English to Indonesian
      await supabase.from('item_meanings').update({ meaning: translation }).eq('id', row.id);
      updates++;
    }
    
    if ((updates + deletes) % 50 === 0 && (updates + deletes) > 0) {
      console.log(`  Progress: ${updates} updated, ${deletes} deleted, ${skipped} skipped...`);
    }
  }
  
  console.log(`\nDone: ${updates} updated, ${deletes} deleted, ${skipped} skipped (no translation found)`);
}

async function main() {
  console.log('=== Fixing Vocabulary Meanings ===\n');
  await fixVocabMeanings();
  console.log('\n✅ Complete!');
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
