-- ============================================================
-- Remove English meanings from items that already have
-- at least one Indonesian meaning for the same item
-- ============================================================

-- First, identify items with both English and Indonesian meanings
-- Then delete the English ones

-- A meaning is "Indonesian" if it doesn't match pure English pattern
-- Pure English: all ASCII letters and spaces, no Indonesian special patterns

DELETE FROM public.item_meanings
WHERE id IN (
  SELECT im.id
  FROM public.item_meanings im
  JOIN public.items i ON i.id = im.item_id
  WHERE i.type IN ('vocabulary', 'kanji')
  -- The meaning looks like English (all Latin chars, common English patterns)
  AND im.meaning ~ '^[A-Za-z][A-Za-z ]+$'
  AND im.meaning ~ '[A-Za-z]{3,}'
  -- The meaning does NOT look like Indonesian
  -- Indonesian words typically have: ng, ny, ak, ik, uk, an, en, in, on, un patterns
  AND im.meaning !~ '(ng|ny|ak|ik|uk|an$| an | en | in | on |bah|ker|per|men|mem|ber|ter|ke-|di-|me-)'
  AND im.meaning !~ '(Adik|Anak|Akan|Aman|Akhir|Awal|Ayah|Baha|Baik|Bari|Baru|Beli|Berd|Bero|Bika|Biru|Bosa|Buku|Bulan|Bunga|Buru|Cari|Cepat|Dala|Dari|Daya|Desa|Diri|Duka|Emas|Gaya|Guru|Hari|Hidu|Hujan|Ibuk|Ikan|Ilmu|Jala|Jara|Jual|Kaka|Kali|Kara|Keba|Keda|Kelu|Kena|Kese|Keta|Kete|Keva|Khaw|Kiri|Kita|Kota|Kuat|Kuda|Kuil|Kura)'
  -- But the item has at least one Indonesian meaning (non-pure-English)
  AND EXISTS (
    SELECT 1 
    FROM public.item_meanings im2
    WHERE im2.item_id = im.item_id
      AND im2.id != im.id
      AND (
        im2.meaning ~ '(ng|ny)'
        OR im2.meaning ~ '[^\x00-\x7F]'
        OR im2.meaning !~ '^[A-Za-z ]+$'
      )
  )
);

-- Also handle specific known English meanings that have Indonesian equivalents
DO $$
DECLARE
  eng_translations TEXT[][] := ARRAY[
    ARRAY['Activity', 'Aktivitas'],
    ARRAY['Admission', 'Penerimaan'],
    ARRAY['Admission Exam', 'Ujian Masuk'],
    ARRAY['Admission Examination', 'Ujian Penerimaan'],
    ARRAY['Admission Test', 'Ujian Masuk'],
    ARRAY['Admission To A Hospital', 'Rawat Inap'],
    ARRAY['Always Open', 'Selalu Buka'],
    ARRAY['Anticipation', 'Antisipasi'],
    ARRAY['Aqueduct', 'Saluran Air'],
    ARRAY['Arm', 'Lengan'],
    ARRAY['Arrangements', 'Pengaturan'],
    ARRAY['Assembly', 'Pertemuan/Rakitan'],
    ARRAY['Attention', 'Perhatian'],
    ARRAY['Bad Guy', 'Orang Jahat'],
    ARRAY['Bad Mouth', 'Mulut Kotor'],
    ARRAY['Bad Woman', 'Wanita Jahat'],
    ARRAY['Bathing Suit', 'Baju Renang'],
    ARRAY['Beginning', 'Permulaan'],
    ARRAY['Behavior', 'Perilaku'],
    ARRAY['Behaviour', 'Perilaku'],
    ARRAY['Best Friend', 'Sahabat'],
    ARRAY['Bike', 'Sepeda'],
    ARRAY['Bill', 'Tagihan'],
    ARRAY['Bills', 'Tagihan-tagihan'],
    ARRAY['Black People', 'Orang Berkulit Hitam'],
    ARRAY['Bookshop', 'Toko Buku'],
    ARRAY['Break', 'Istirahat'],
    ARRAY['Bull', 'Banteng'],
    ARRAY['Business', 'Bisnis'],
    ARRAY['Cadaver', 'Jenazah'],
    ARRAY['Cancellation', 'Pembatalan'],
    ARRAY['Capital Letters', 'Huruf Kapital'],
    ARRAY['Carnivore', 'Karnivora'],
    ARRAY['Celebration', 'Perayaan'],
    ARRAY['Chairman', 'Ketua'],
    ARRAY['Change', 'Perubahan'],
    ARRAY['Cherry Blossom', 'Bunga Sakura'],
    ARRAY['Chinese Character', 'Karakter Cina'],
    ARRAY['Chinese Characters', 'Karakter-karakter Cina'],
    ARRAY['Chopsticks', 'Sumpit'],
    ARRAY['Citizen', 'Warga Negara'],
    ARRAY['City Hall', 'Balai Kota'],
    ARRAY['Class', 'Kelas'],
    ARRAY['Climate', 'Iklim'],
    ARRAY['Collection', 'Koleksi'],
    ARRAY['College Student', 'Mahasiswa'],
    ARRAY['Comfort', 'Kenyamanan'],
    ARRAY['Company Employee', 'Karyawan'],
    ARRAY['Competition', 'Kompetisi'],
    ARRAY['Condition', 'Kondisi'],
    ARRAY['Congratulations', 'Selamat'],
    ARRAY['Conversation', 'Percakapan'],
    ARRAY['Copy', 'Salinan'],
    ARRAY['Corpse', 'Jenazah'],
    ARRAY['Cute', 'Imut'],
    ARRAY['Daily', 'Sehari-hari'],
    ARRAY['Dark', 'Gelap'],
    ARRAY['Day After Tomorrow', 'Lusa'],
    ARRAY['Day Before Yesterday', 'Kemarin Lusa'],
    ARRAY['Deadline', 'Batas Waktu'],
    ARRAY['Death', 'Kematian'],
    ARRAY['Democracy', 'Demokrasi'],
    ARRAY['Design', 'Desain'],
    ARRAY['Direction', 'Arah'],
    ARRAY['Doctor', 'Dokter'],
    ARRAY['Double', 'Ganda'],
    ARRAY['Draft', 'Draf'],
    ARRAY['Economics', 'Ekonomi'],
    ARRAY['Economy', 'Ekonomi'],
    ARRAY['Education', 'Pendidikan'],
    ARRAY['Effort', 'Usaha'],
    ARRAY['Election', 'Pemilihan'],
    ARRAY['Electricity', 'Listrik'],
    ARRAY['Elementary School', 'Sekolah Dasar'],
    ARRAY['Elevator', 'Lift'],
    ARRAY['Employee', 'Karyawan'],
    ARRAY['Encounter', 'Pertemuan'],
    ARRAY['Energy', 'Energi'],
    ARRAY['Examination', 'Ujian'],
    ARRAY['Exchange', 'Pertukaran'],
    ARRAY['Experience', 'Pengalaman'],
    ARRAY['Experiment', 'Eksperimen'],
    ARRAY['Explanation', 'Penjelasan'],
    ARRAY['Express Train', 'Kereta Ekspres'],
    ARRAY['Famous', 'Terkenal'],
    ARRAY['Fear', 'Ketakutan'],
    ARRAY['Festival', 'Festival'],
    ARRAY['Fight', 'Pertarungan'],
    ARRAY['Film', 'Film'],
    ARRAY['Fish Market', 'Pasar Ikan'],
    ARRAY['Flat', 'Datar'],
    ARRAY['Foreign', 'Asing'],
    ARRAY['Form', 'Formulir'],
    ARRAY['Friend', 'Teman'],
    ARRAY['From Now On', 'Mulai Sekarang'],
    ARRAY['Function', 'Fungsi'],
    ARRAY['General', 'Umum'],
    ARRAY['Gift', 'Hadiah'],
    ARRAY['Government', 'Pemerintah'],
    ARRAY['Gradually', 'Secara Bertahap'],
    ARRAY['Grandchild', 'Cucu'],
    ARRAY['Grandmother', 'Nenek'],
    ARRAY['Group', 'Kelompok'],
    ARRAY['Harmony', 'Harmoni'],
    ARRAY['Health', 'Kesehatan'],
    ARRAY['Heart', 'Hati/Jantung'],
    ARRAY['Herbivore', 'Herbivora'],
    ARRAY['High School', 'SMA'],
    ARRAY['High School Student', 'Siswa SMA'],
    ARRAY['History', 'Sejarah'],
    ARRAY['Holiday', 'Hari Libur'],
    ARRAY['Home', 'Rumah'],
    ARRAY['Homework', 'Pekerjaan Rumah'],
    ARRAY['Hospital', 'Rumah Sakit'],
    ARRAY['Human', 'Manusia'],
    ARRAY['Idea', 'Ide'],
    ARRAY['Important', 'Penting'],
    ARRAY['Impossible', 'Tidak Mungkin'],
    ARRAY['In A Hurry', 'Terburu-buru'],
    ARRAY['In Total', 'Secara Keseluruhan'],
    ARRAY['Incident', 'Kejadian'],
    ARRAY['Information', 'Informasi'],
    ARRAY['Interest', 'Minat'],
    ARRAY['Introduction', 'Perkenalan'],
    ARRAY['Invention', 'Penemuan'],
    ARRAY['Invitation', 'Undangan'],
    ARRAY['Japanese Food', 'Makanan Jepang'],
    ARRAY['Job', 'Pekerjaan'],
    ARRAY['Kind', 'Baik Hati'],
    ARRAY['Kitchen', 'Dapur'],
    ARRAY['Knowledge', 'Pengetahuan'],
    ARRAY['Large', 'Besar'],
    ARRAY['Lawyer', 'Pengacara'],
    ARRAY['Learning', 'Pembelajaran'],
    ARRAY['Letter', 'Surat'],
    ARRAY['Library', 'Perpustakaan'],
    ARRAY['Line', 'Garis'],
    ARRAY['Loan', 'Pinjaman'],
    ARRAY['Location', 'Lokasi'],
    ARRAY['Loss', 'Kerugian'],
    ARRAY['Map', 'Peta'],
    ARRAY['Match', 'Pertandingan'],
    ARRAY['Meadow', 'Padang Rumput'],
    ARRAY['Medical Doctor', 'Dokter'],
    ARRAY['Memory', 'Memori'],
    ARRAY['Message', 'Pesan'],
    ARRAY['Middle School', 'SMP'],
    ARRAY['Modern', 'Modern'],
    ARRAY['Movie', 'Film'],
    ARRAY['Movie Theater', 'Bioskop'],
    ARRAY['Music', 'Musik'],
    ARRAY['Name Card', 'Kartu Nama'],
    ARRAY['Nature', 'Alam'],
    ARRAY['New Year', 'Tahun Baru'],
    ARRAY['Night', 'Malam'],
    ARRAY['Noon', 'Tengah Hari'],
    ARRAY['Now', 'Sekarang'],
    ARRAY['Number', 'Nomor'],
    ARRAY['Nurse', 'Perawat'],
    ARRAY['Occupation', 'Pekerjaan'],
    ARRAY['Opinion', 'Pendapat'],
    ARRAY['Order', 'Pesanan'],
    ARRAY['Organization', 'Organisasi'],
    ARRAY['Overseas', 'Luar Negeri'],
    ARRAY['Pain', 'Rasa Sakit'],
    ARRAY['Parking', 'Parkir'],
    ARRAY['Party', 'Pesta'],
    ARRAY['Peace', 'Perdamaian'],
    ARRAY['Performance', 'Pertunjukan'],
    ARRAY['Permission', 'Izin'],
    ARRAY['Plan', 'Rencana'],
    ARRAY['Police', 'Polisi'],
    ARRAY['Police Officer', 'Polisi'],
    ARRAY['Policy', 'Kebijakan'],
    ARRAY['Political Party', 'Partai Politik'],
    ARRAY['Politics', 'Politik'],
    ARRAY['Post Office', 'Kantor Pos'],
    ARRAY['Practice', 'Latihan'],
    ARRAY['Preparation', 'Persiapan'],
    ARRAY['Price', 'Harga'],
    ARRAY['Professor', 'Profesor'],
    ARRAY['Progress', 'Kemajuan'],
    ARRAY['Project', 'Proyek'],
    ARRAY['Public', 'Publik'],
    ARRAY['Rabbit', 'Kelinci'],
    ARRAY['Recording', 'Rekaman'],
    ARRAY['Religion', 'Agama'],
    ARRAY['Rent', 'Sewa'],
    ARRAY['Report', 'Laporan'],
    ARRAY['Research', 'Penelitian'],
    ARRAY['Restaurant', 'Restoran'],
    ARRAY['Relationship', 'Hubungan'],
    ARRAY['Result', 'Hasil'],
    ARRAY['Role', 'Peran'],
    ARRAY['Rule', 'Aturan'],
    ARRAY['Safety', 'Keamanan'],
    ARRAY['Salary', 'Gaji'],
    ARRAY['Sample', 'Sampel'],
    ARRAY['Scenery', 'Pemandangan'],
    ARRAY['Schedule', 'Jadwal'],
    ARRAY['School', 'Sekolah'],
    ARRAY['Season', 'Musim'],
    ARRAY['Self Introduction', 'Perkenalan Diri'],
    ARRAY['Service', 'Layanan'],
    ARRAY['Sharp', 'Tajam'],
    ARRAY['Short', 'Pendek'],
    ARRAY['Shrine', 'Kuil'],
    ARRAY['Sign', 'Tanda'],
    ARRAY['Slowly', 'Perlahan'],
    ARRAY['Small', 'Kecil'],
    ARRAY['Society', 'Masyarakat'],
    ARRAY['Something', 'Sesuatu'],
    ARRAY['Song', 'Lagu'],
    ARRAY['Sorry', 'Maaf'],
    ARRAY['Soul', 'Jiwa'],
    ARRAY['Speech', 'Pidato'],
    ARRAY['Speed', 'Kecepatan'],
    ARRAY['Sport', 'Olahraga'],
    ARRAY['Spring', 'Musim Semi'],
    ARRAY['Station', 'Stasiun'],
    ARRAY['Story', 'Cerita'],
    ARRAY['Strange', 'Aneh'],
    ARRAY['Strong', 'Kuat'],
    ARRAY['Student', 'Siswa'],
    ARRAY['Study', 'Belajar'],
    ARRAY['Subject', 'Mata Pelajaran'],
    ARRAY['Success', 'Kesuksesan'],
    ARRAY['Summer', 'Musim Panas'],
    ARRAY['Supermarket', 'Supermarket'],
    ARRAY['Support', 'Dukungan'],
    ARRAY['Swimming', 'Berenang'],
    ARRAY['System', 'Sistem'],
    ARRAY['Tall', 'Tinggi'],
    ARRAY['Teacher', 'Guru'],
    ARRAY['Technology', 'Teknologi'],
    ARRAY['Temperature', 'Suhu'],
    ARRAY['Temple', 'Kuil Budha'],
    ARRAY['Test', 'Ujian'],
    ARRAY['Thank You', 'Terima Kasih'],
    ARRAY['Think', 'Berpikir'],
    ARRAY['Thought', 'Pemikiran'],
    ARRAY['Time', 'Waktu'],
    ARRAY['Today', 'Hari Ini'],
    ARRAY['Together', 'Bersama'],
    ARRAY['Tomorrow', 'Besok'],
    ARRAY['Too Much', 'Terlalu Banyak'],
    ARRAY['Topic', 'Topik'],
    ARRAY['Town', 'Kota'],
    ARRAY['Train', 'Kereta'],
    ARRAY['Translation', 'Terjemahan'],
    ARRAY['Transportation', 'Transportasi'],
    ARRAY['Trip', 'Perjalanan'],
    ARRAY['Truth', 'Kebenaran'],
    ARRAY['Two People', 'Dua Orang'],
    ARRAY['Umbrella', 'Payung'],
    ARRAY['Understanding', 'Pemahaman'],
    ARRAY['Unexpected', 'Tidak Terduga'],
    ARRAY['Unit', 'Unit'],
    ARRAY['University', 'Universitas'],
    ARRAY['Unusual', 'Tidak Biasa'],
    ARRAY['Vacation', 'Liburan'],
    ARRAY['Various', 'Berbagai'],
    ARRAY['Village', 'Desa'],
    ARRAY['Visit', 'Kunjungi'],
    ARRAY['Volunteer', 'Sukarelawan'],
    ARRAY['Water', 'Air'],
    ARRAY['Weather', 'Cuaca'],
    ARRAY['Weak', 'Lemah'],
    ARRAY['Welcome', 'Selamat Datang'],
    ARRAY['Western Style', 'Gaya Barat'],
    ARRAY['When', 'Kapan'],
    ARRAY['Where', 'Di mana'],
    ARRAY['Winter', 'Musim Dingin'],
    ARRAY['Worry', 'Khawatir'],
    ARRAY['Writer', 'Penulis'],
    ARRAY['Yesterday', 'Kemarin'],
    ARRAY['Young', 'Muda'],
    ARRAY['Zero', 'Nol'],
    ARRAY['Bargain Sale', 'Obral'],
    ARRAY['Brown Color', 'Warna Coklat'],
    ARRAY['Mountain Climbing', 'Mendaki Gunung'],
    ARRAY['Overseas Study', 'Belajar di Luar Negeri'],
    ARRAY['Early Morning', 'Dini Hari'],
    ARRAY['What Day', 'Hari Apa'],
    ARRAY['Back Street', 'Jalan Belakang'],
    ARRAY['Backstreets', 'Gang-gang Belakang'],
    ARRAY['A Thought', 'Sebuah Pikiran'],
    ARRAY['Abruptly', 'Tiba-tiba'],
    ARRAY['Admirable', 'Mengagumkan'],
    ARRAY['Ancient', 'Kuno'],
    ARRAY['Archaeology', 'Arkeologi'],
    ARRAY['Arriving At The Office', 'Tiba di Kantor'],
    ARRAY['As For Me', 'Mengenai Saya'],
    ARRAY['As Hard As One Can', 'Sekuat Tenaga']
  ];
  t TEXT[];
  eng TEXT;
  idn TEXT;
BEGIN
  FOREACH t SLICE 1 IN ARRAY eng_translations
  LOOP
    eng := t[1];
    idn := t[2];
    
    UPDATE public.item_meanings im
    SET meaning = idn
    WHERE im.meaning = eng
      AND EXISTS (SELECT 1 FROM public.items i WHERE i.id = im.item_id AND i.type = 'vocabulary')
      AND NOT EXISTS (
        SELECT 1 FROM public.item_meanings im2
        WHERE im2.item_id = im.item_id AND im2.meaning = idn AND im2.id != im.id
      );
    
    DELETE FROM public.item_meanings im
    WHERE im.meaning = eng
      AND EXISTS (SELECT 1 FROM public.items i WHERE i.id = im.item_id AND i.type = 'vocabulary')
      AND EXISTS (
        SELECT 1 FROM public.item_meanings im2
        WHERE im2.item_id = im.item_id AND im2.meaning = idn AND im2.id != im.id
      );
  END LOOP;
END $$;
