INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('852c7c14-8884-4b77-8c65-e27d6d23c724', '方言のじしょを作っています。', 'Saya sedang membuat kamus dialek.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('852c7c14-8884-4b77-8c65-e27d6d23c724', 'ああっもうっ！かれしの方言がうつっちゃってるずら。', 'Berengsek! Dialek pacar saya telah menular ke saya.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('852c7c14-8884-4b77-8c65-e27d6d23c724', '私の国の東側出身の人達は変わった方言で喋るので、彼らが何を言っているのか全く分かりません。', 'Orang-orang dari bagian timur negara saya menggunakan dialek yang aneh sehingga mereka tidak mungkin memahaminya.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('5e7688f3-ae65-4d67-95e1-c63e2b87de3e', 'vocabulary', '手作り', '手作り', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Sesuatu yang dibuat dengan tangan berarti buatan tangan!', 'Sesuatu yang dibuat dengan tangan berarti buatan tangan!') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('5e7688f3-ae65-4d67-95e1-c63e2b87de3e', 'buatan tangan', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('5e7688f3-ae65-4d67-95e1-c63e2b87de3e', 'Homemade', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('5e7688f3-ae65-4d67-95e1-c63e2b87de3e', 'てづくり', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5e7688f3-ae65-4d67-95e1-c63e2b87de3e', 'このテーブルは、林さんの手作りです。', 'Meja ini buatan tangan oleh Hayashi.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5e7688f3-ae65-4d67-95e1-c63e2b87de3e', '毎日手作りのバランスのいい食じをとるようにしています。', 'Saya mencoba menjalani pola makan buatan sendiri yang seimbang setiap hari.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5e7688f3-ae65-4d67-95e1-c63e2b87de3e', '手作りのプレゼントは、どれだけ暇な時間があるかってことがバレてしまうので、結構怖い。', 'Hadiah buatan tangan cukup menakutkan karena menunjukkan bahwa Anda memiliki terlalu banyak waktu luang.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'vocabulary', '近づく', '近づく', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Karena kata ini diakhiri dengan bunyi う, Anda dapat mengetahui kemungkinan itu adalah kata kerja. Bagian kanji artinya dekat. Versi kata kerjanya adalah mendekat, mendekat, atau mendekat. Pada dasarnya, gagasan umumnya adalah Anda semakin dekat dengan sesuatu. Anda menjadi lebih dekat. Anda mendekat.', 'Karena kata ini diakhiri dengan bunyi う, Anda dapat mengetahui kemungkinan itu adalah kata kerja. Bagian kanji artinya dekat. Versi kata kerjanya adalah mendekat, mendekat, atau mendekat. Pada dasarnya, gagasan umumnya adalah Anda semakin dekat dengan sesuatu. Anda menjadi lebih dekat. Anda mendekat.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'Untuk Mendekat', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'To Approach', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'To Draw Near', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'To Near', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'To Bring Near', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'ちかづく', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'カメラマンが近づくとカメはにげてしまった。', 'Saat juru kamera mendekatinya, penyu tersebut lari.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', 'おれの女に近づくな！', 'Jangan mendekati pacarku!') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa9aa47f-a751-4eed-8a1f-e4dfb31c555e', '私達に今近づいてきているゾンビ、めちゃくちゃ私のタイプなんだけど。', 'Anehnya, zombie yang mendekati kita saat ini sebenarnya adalah tipeku.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'vocabulary', '言い方', '言い方', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Cara mengatakan sesuatu adalah cara Anda mengatakannya. Ini bisa jadi aksen Anda atau cara Anda berbicara.', 'Cara mengatakan sesuatu adalah cara Anda mengatakannya. Ini bisa jadi aksen Anda atau cara Anda berbicara.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'Cara Mengatakan', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'Way Of Talking', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'Speaking Style', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'いいかた', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'そうは言っても、言い方ってもんがあるだろ！', 'Itu masuk akal, tetapi Anda harus memikirkan cara Anda mengatakan sesuatu!') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'そうだ、話はかわるんだけど、コウイチのネコって言ばの言い方、めっちゃかわいくない？', 'Oh, maaf karena mengubah topik pembicaraan, tapi tidakkah menurutmu cara Koichi mengucapkan kata kucing itu lucu sekali?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('71a300c7-ed70-4050-b69d-f14a7c796638', 'あなたの物の言い方はとても馬鹿です。', 'Caramu mengatakan itu sangat bodoh.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'vocabulary', '早口', '早口', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Jika Anda mempunyai mulut yang cepat, kemungkinan besar Anda adalah orang yang cepat bicara, bukan?', 'Jika Anda mempunyai mulut yang cepat, kemungkinan besar Anda adalah orang yang cepat bicara, bukan?') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'Pembicara Cepat', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'Fast Talking', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'Fast Speaker', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'Fast Speaking', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'はやくち', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'わたしの兄は、とても早口です。', 'Kakak laki-laki saya adalah pembicara yang sangat cepat.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'お前のことが一ばん大すきだよって、何でそんなに早口で言ったの？', 'Mengapa kamu mengatakan bahwa kamu paling mencintaiku begitu cepat?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('c843c0e1-f697-45be-9a90-67c127002649', 'こんなに早口の赤ん坊なんて見たことないよ。', 'Saya belum pernah melihat bayi yang berbicara secepat ini sebelumnya.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'vocabulary', '足りない', '足りない', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Anda tahu kata 足りる dari Level 4. Kata apa ini? justru sebaliknya (bentuk negatif pada kata kerja adalah ない). Jadi, apa lawan kata dari 足りる (Mencukupkan)? Kebalikannya adalah tidak cukup atau tidak cukup.', 'Anda tahu kata 足りる dari Level 4. Kata apa ini? justru sebaliknya (bentuk negatif pada kata kerja adalah ない). Jadi, apa lawan kata dari 足りる (Mencukupkan)? Kebalikannya adalah tidak cukup atau tidak cukup.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'Tidak Cukup', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'Insufficient', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'Not Sufficient', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'たりない', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'お金が十円足りないんです。', 'Aku kekurangan sepuluh yen.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'もしスペースが足りなければ、べつの用しについきして、それをてんぷしてください。', 'Jika ruang tidak mencukupi, lampirkan lembar terpisah dengan informasi tambahan.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('7992b16c-53f1-4be1-9a37-7e4c3526cd92', 'ビル・ゲイツは私の息子なのだが、それを証明するための証拠がまだ足りない。', 'Bill Gates adalah anak saya, tapi belum cukup bukti untuk membuktikannya.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', 'vocabulary', '近々', '近々', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Ketika sesuatu sudah dekat (karakter 々 mengulangi kanji sebelumnya) itu akan terjadi dalam waktu dekat, atau segera. 

Ini sangat tidak jelas, dan tergantung pada orang yang berbicara untuk memutuskan seberapa cepatnya. Tergantung pada orang dan situasinya, secara teknis dapat digunakan untuk apa pun hingga beberapa tahun!', 'Ketika sesuatu sudah dekat (karakter 々 mengulangi kanji sebelumnya) itu akan terjadi dalam waktu dekat, atau segera. 

Ini sangat tidak jelas, dan tergantung pada orang yang berbicara untuk memutuskan seberapa cepatnya. Tergantung pada orang dan situasinya, secara teknis dapat digunakan untuk apa pun hingga beberapa tahun!') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', 'Dalam Waktu Dekat', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', 'Soon', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', 'ちかぢか', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', 'きんきん', NULL, false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', 'それについては、近々はっぴょうがあると思いますよ。', 'Saya pikir akan ada pengumuman tentang hal itu segera.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', '近々雪がふるはずなので、たくさんつもったらかまくらを作ります。', 'Seharusnya kita akan segera mendapat salju, jadi kalau banyak, aku akan membuat igloo salju.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('aea7f0c9-0731-4902-995d-3cedb9ceed32', 'もしタバコを吸い続けるなら、あなたは近々癌を発症するでしょう。', 'Anda akan terkena kanker dalam waktu dekat jika Anda terus merokok.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', 'vocabulary', '作り方', '作り方', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Inilah cara untuk membuat sesuatu. Inilah cara membuat sesuatu. Anda akan melihat ini untuk petunjuk dalam membangun sesuatu.', 'Inilah cara untuk membuat sesuatu. Inilah cara membuat sesuatu. Anda akan melihat ini untuk petunjuk dalam membangun sesuatu.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', 'Cara Membuat', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', 'Way To Make', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', 'Way Of Making', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', 'つくりかた', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', 'おいしいマカロニチーズの作り方を教えてください。', 'Tolong ajari saya cara membuat makaroni dan keju yang enak.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', '麦茶の作り方には、おゆでわかしながらに出す方ほう、ふっとうさせたおゆでジワジワおゆ出しする方ほう、つめたい水でジワジワ水出しする方ほうの三しゅるいありますが、それぞれメリットデメリットがあります。', 'Ada tiga cara membuat teh jelai; merendamnya dalam air mendidih, merendamnya perlahan dalam air matang, dan merendamnya perlahan dalam air dingin, dan masing-masing memiliki kelebihan dan kekurangan.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('67bad6a7-6e4c-4fb0-b040-4396baa260fc', '手裏剣の作り方を知りたいですか？', 'Ingin tahu cara membuat bintang ninja?') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'vocabulary', '出会う', '出会う', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Anda keluar dari rumah Anda dan bertemu seseorang. Anda tidak bermaksud untuk bertemu mereka, tetapi hal itu tetap terjadi. Itu sebabnya kata ini berarti bertemu secara kebetulan.', 'Anda keluar dari rumah Anda dan bertemu seseorang. Anda tidak bermaksud untuk bertemu mereka, tetapi hal itu tetap terjadi. Itu sebabnya kata ini berarti bertemu secara kebetulan.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'Bertemu Secara Kebetulan', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'To Meet Unexpectedly', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'To Come Across', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'To Encounter', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'To Run Into', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'であう', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'わたしたち、ちょっと出会うのが早すぎたみたいね。', 'Sepertinya kami bertemu satu sama lain terlalu dini.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', 'きのうの夜、クラブで、れんあいかんじょうぬきでただ楽しみたいっていう男に出会ってさ、ハマっちゃいけないのは分かってるけど、めちゃくちゃタイプだったんだよね。', 'Tadi malam, aku bertemu pria yang mencari kesenangan tanpa pamrih di klub dan aku tahu aku tidak seharusnya menyukainya, tapi dia benar-benar tipeku.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('466e7394-14ed-4417-9b40-5081b575f0c1', '「ニコールって、今、付き合っている人いるの？」「ええ。エリックと1年間付き合っているわ。」「そうなんだ！彼とは、どこで出会ったの？」', '"Apakah kamu sedang berkencan dengan seseorang sekarang, Nicole?" "Ya, aku sudah bertemu Eric selama setahun." "Wow, di mana kalian bertemu?"') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', 'vocabulary', '私', '私', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Kanji dan kata-katanya sama persis. Itu berarti mereka juga berbagi makna.', 'Kanji dan kata-katanya sama persis. Itu berarti mereka juga berbagi makna.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', 'saya', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', 'Me', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', 'わたし', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', 'わたくし', NULL, false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', 'メーリングリストから私を外してください。', 'Tolong hapus saya dari daftar email Anda.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', '私がえいぎょう部のせきにん者です。', 'Saya direktur divisi penjualan.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('b56a8c95-175d-4f22-9fd4-57f8fc56d9b0', '昨日の夜、バーデビューしちゃった。私もちょっとずつ大人の階段登ってるって感じ？', 'Saya pergi ke bar untuk pertama kalinya tadi malam. Saya merasa seperti saya perlahan menjadi dewasa.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('fa5983c4-4a9b-4a0b-8010-0c2737aba61e', 'vocabulary', '私立', '私立', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Tempatku berdiri adalah area pribadiku. Pikirkan tentang "lingkaran ruang pribadi". Di sinilah Anda berdiri ditambah jarak satu lengan. Area ini sangat pribadi bagi Anda. Siapa yang tahu apa yang Anda lakukan di area pribadi Anda.', 'Tempatku berdiri adalah area pribadiku. Pikirkan tentang "lingkaran ruang pribadi". Di sinilah Anda berdiri ditambah jarak satu lengan. Area ini sangat pribadi bagi Anda. Siapa yang tahu apa yang Anda lakukan di area pribadi Anda.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa5983c4-4a9b-4a0b-8010-0c2737aba61e', 'Pribadi', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('fa5983c4-4a9b-4a0b-8010-0c2737aba61e', 'しりつ', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa5983c4-4a9b-4a0b-8010-0c2737aba61e', '私立のようちえんはクリスマスの日はお休みだよ。', 'Taman kanak-kanak swasta tutup pada Hari Natal.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa5983c4-4a9b-4a0b-8010-0c2737aba61e', 'ここを出て、前の通りを左の方へ三つ目の交さ点まで歩くと、その私立病院に着きますよ。', 'Keluar dari sini dan berjalan ke kiri sepanjang jalan sampai Anda tiba di persimpangan ketiga dan Anda akan sampai ke rumah sakit swasta.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa5983c4-4a9b-4a0b-8010-0c2737aba61e', 'コウイチがカフェでこっそり会っていた男の人は、私立探偵だったということが判明しました。', 'Saya mengetahui bahwa pria yang diam-diam ditemui Koichi di kafe adalah seorang detektif swasta.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', 'vocabulary', '私自身', '私自身', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', '"Jika menyangkut orang seperti diriku... alias aku..." Ketika kamu mengatakan ini, kamu sebenarnya mengatakan "secara pribadi" atau "untuk aku".', '"Jika menyangkut orang seperti diriku... alias aku..." Ketika kamu mengatakan ini, kamu sebenarnya mengatakan "secara pribadi" atau "untuk aku".') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', 'Secara pribadi', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', 'As For Me', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', 'Myself', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', 'わたしじしん', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', 'わたくしじしん', NULL, false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', '私自身は、その動物園の問題にはあまり関心がないんです。', 'Secara pribadi, saya tidak peduli dengan masalah kebun binatang.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', '私自身は、そんなにきょくたんなことじゃなければ、どんな食生活でも良いと思っています。', 'Bagi saya, asalkan tidak terlalu ekstrem, saya rasa diet apa pun boleh-boleh saja.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('43f31045-9b91-4600-bed3-2b61af36d107', 'あなたがもし私自身よりも私のことを知っていると思ったら、 それはとんだ大間違いよ。', 'Kamu salah besar jika kamu pikir kamu mengenalku lebih baik daripada aku mengenal diriku sendiri.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('8c896604-435f-43ba-8b6e-2e52842cba07', 'vocabulary', '私立大学', '私立大学', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Anda pernah melihat 私立, yang berarti "swasta", dan Anda pernah melihat 大学, yang berarti "perguruan tinggi" atau "universitas". Jadi, gabungkan keduanya dan Anda memiliki perguruan tinggi swasta/universitas swasta.', 'Anda pernah melihat 私立, yang berarti "swasta", dan Anda pernah melihat 大学, yang berarti "perguruan tinggi" atau "universitas". Jadi, gabungkan keduanya dan Anda memiliki perguruan tinggi swasta/universitas swasta.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('8c896604-435f-43ba-8b6e-2e52842cba07', 'Perguruan Tinggi Swasta', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('8c896604-435f-43ba-8b6e-2e52842cba07', 'Private University', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('8c896604-435f-43ba-8b6e-2e52842cba07', 'しりつだいがく', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('8c896604-435f-43ba-8b6e-2e52842cba07', '私立大学は公立大学よりじゅ業料が高いです。', 'Biaya kuliah di perguruan tinggi swasta lebih mahal dibandingkan dengan perguruan tinggi negeri.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('8c896604-435f-43ba-8b6e-2e52842cba07', 'わせ田大学は日本の有名な私立大学です。', 'Universitas Waseda adalah universitas swasta terkenal di Jepang.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('8c896604-435f-43ba-8b6e-2e52842cba07', 'あの出火した私立大学は、私が通っている学校だよ。', 'Perguruan tinggi swasta yang sedang on fire adalah perguruan tinggi yang saya ikuti saat ini.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', 'vocabulary', '私大', '私大', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Anda tahu bagaimana 私 bisa berarti pribadi dan bagaimana 大 adalah bagian pertama dari 大学? Nah, gabungkan keduanya dan Anda akan mendapatkan versi singkat dari perguruan tinggi swasta atau universitas swasta.', 'Anda tahu bagaimana 私 bisa berarti pribadi dan bagaimana 大 adalah bagian pertama dari 大学? Nah, gabungkan keduanya dan Anda akan mendapatkan versi singkat dari perguruan tinggi swasta atau universitas swasta.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', 'Perguruan Tinggi Swasta', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', 'Private University', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', 'Private Uni', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', 'しだい', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', '私大の授業料は高いもんね。', 'Biaya kuliah swasta memang mahal.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', 'とある大阪の私大で英語を教えています。', 'Saya mengajar bahasa Inggris di universitas swasta di Osaka.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('965a077b-c27e-49a0-8499-08c110015d6d', 'こないだ言ってた私大の学園祭の件なんだけど、今回は私の事数にいれないで。ごめん。でも悪く思わないでね。時間ができたら連絡するから。', 'Mengenai festival sekolah di universitas swasta yang Anda ceritakan kemarin, bisakah Anda mengabaikan saya kali ini? Maafkan aku, jangan marah padaku. Saya akan menghubungi Anda ketika saya punya waktu luang.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', 'vocabulary', '広がる', '広がる', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Ingat? Ya beginilah, kecuali kata kerjanya. Ketika sesuatu melakukan tindakan melebar, itu berarti menyebar, meluas, atau meregang.

Anda sudah mempelajari 広げる, yang digunakan saat ANDA menyebarkan sesuatu. 広がる, sebaliknya, berarti sesuatu menyebar dengan sendirinya. Perlu disebutkan bahwa banyak kata kerja intransitif yang diakhiri dengan がる, dan ini tidak terkecuali. Bayangkan saja bagaimana dengan seorang gadis (がる) yang kamu tahu bisa melakukan segalanya sendirian. Dia tidak pernah membutuhkan bantuan dari orang lain.', 'Ingat? Ya beginilah, kecuali kata kerjanya. Ketika sesuatu melakukan tindakan melebar, itu berarti menyebar, meluas, atau meregang.

Anda sudah mempelajari 広げる, yang digunakan saat ANDA menyebarkan sesuatu. 広がる, sebaliknya, berarti sesuatu menyebar dengan sendirinya. Perlu disebutkan bahwa banyak kata kerja intransitif yang diakhiri dengan がる, dan ini tidak terkecuali. Bayangkan saja bagaimana dengan seorang gadis (がる) yang kamu tahu bisa melakukan segalanya sendirian. Dia tidak pernah membutuhkan bantuan dari orang lain.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', 'Untuk Menyebar', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', 'To Extend', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', 'To Stretch', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', 'ひろがる', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', 'ごめんなさい。ジーンズのせいで私の足はこれ以上広がりません。', 'Maaf, celana jinsku tidak bisa melebarkan kakiku lebih jauh.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', 'この山火じは、今しゅうまつにもオレゴンしゅうまで広がってしまうかもしれない。', 'Kebakaran hutan ini mungkin menyebar ke negara bagian Oregon pada akhir minggu ini.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fb572519-bc47-4d4e-9289-10635ff5af0b', '見わたす限りラベンダ畑が広がっていた。', 'Ladang lavender terbentang sejauh mata memandang.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('cc680f63-748b-4726-a57a-f0b4ce6bb6f3', 'vocabulary', '身', '身', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Kanjinya adalah seseorang, tetapi kata-katanya adalah tubuh. Saya kira seseorang adalah tubuh seseorang, jadi setidaknya mereka serupa.', 'Kanjinya adalah seseorang, tetapi kata-katanya adalah tubuh. Saya kira seseorang adalah tubuh seseorang, jadi setidaknya mereka serupa.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('cc680f63-748b-4726-a57a-f0b4ce6bb6f3', 'Tubuh', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('cc680f63-748b-4726-a57a-f0b4ce6bb6f3', 'Oneself', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('cc680f63-748b-4726-a57a-f0b4ce6bb6f3', 'み', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('cc680f63-748b-4726-a57a-f0b4ce6bb6f3', 'リストラで、身も心もズタズタです。', 'Karena PHK saya, fisik dan mental saya terkoyak.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('cc680f63-748b-4726-a57a-f0b4ce6bb6f3', 'この魚の身はたん白でおいしいね。', 'Daging ikan ini ringan dan enak bukan?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('cc680f63-748b-4726-a57a-f0b4ce6bb6f3', '現金は常に身につけておく方がいい。', 'Anda harus selalu membawa uang tunai.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('5d633797-ca8c-4ae7-b77d-1c2bf975fd3c', 'vocabulary', '社会', '社会', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Jangan bingung dengan 会社, yang merupakan perusahaan, inilah masyarakat. Ketika sebuah perusahaan bertemu bersama, itu seperti sekelompok orang, yang berada dalam kelompok, berkumpul untuk hidup di satu dunia. Itu adalah masyarakat.', 'Jangan bingung dengan 会社, yang merupakan perusahaan, inilah masyarakat. Ketika sebuah perusahaan bertemu bersama, itu seperti sekelompok orang, yang berada dalam kelompok, berkumpul untuk hidup di satu dunia. Itu adalah masyarakat.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('5d633797-ca8c-4ae7-b77d-1c2bf975fd3c', 'Masyarakat', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('5d633797-ca8c-4ae7-b77d-1c2bf975fd3c', 'しゃかい', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5d633797-ca8c-4ae7-b77d-1c2bf975fd3c', '今家を出ても、社会のじゅぎょうに間にあわないと思います。', 'Bahkan jika aku meninggalkan rumah sekarang, aku pikir aku mungkin akan terlambat untuk pelajaran IPS.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5d633797-ca8c-4ae7-b77d-1c2bf975fd3c', '国さい社会の一員として、めしテロにはだんじてくっしません。', 'Sebagai anggota masyarakat internasional, saya tidak akan menyerah pada pornografi makanan.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5d633797-ca8c-4ae7-b77d-1c2bf975fd3c', '社会問題として、若者がお葬式で自分撮りをすることについて考える必要がある。', 'Sebagai masyarakat, kita perlu khawatir terhadap generasi muda yang melakukan ‘selfie’ di pemakaman.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('317abc16-85d4-475e-9a09-230552eb9ff8', 'vocabulary', '言語', '言語', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Saat Anda mengucapkan kata-kata dalam suatu bahasa, Anda sedang berbicara dalam suatu bahasa. Tidak yakin bahasa apa itu, tapi karena Anda mengatakannya, itu pasti nyata.', 'Saat Anda mengucapkan kata-kata dalam suatu bahasa, Anda sedang berbicara dalam suatu bahasa. Tidak yakin bahasa apa itu, tapi karena Anda mengatakannya, itu pasti nyata.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('317abc16-85d4-475e-9a09-230552eb9ff8', 'Bahasa', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('317abc16-85d4-475e-9a09-230552eb9ff8', 'A Language', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('317abc16-85d4-475e-9a09-230552eb9ff8', 'げんご', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('317abc16-85d4-475e-9a09-230552eb9ff8', '今人気のプログラミング言語は何ですか？', 'Apa bahasa pemrograman yang populer saat ini?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('317abc16-85d4-475e-9a09-230552eb9ff8', '言語オタクたちが朝まで言語について語りつくすオフ会にさんかしてきました。', 'Saya bergabung dalam pertemuan offline di mana para ahli bahasa berkumpul dan berbicara tentang bahasa sepanjang malam.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('317abc16-85d4-475e-9a09-230552eb9ff8', '新しいコンピュータ言語の勉強を始めました。', 'Saya mulai mempelajari bahasa komputer baru.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('caa109d7-57f0-444f-b173-30cfea742a26', 'vocabulary', '地上', '地上', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Ingat 地下, yang artinya "di bawah tanah". Nah, ini adalah gabungan antara tanah dan di atas, jadi saya yakin Anda bisa menebak bahwa ini berarti di atas tanah. Namun biasanya benda yang berada di atas tanah tidak mengapung (kecuali jika berada di luar angkasa), sehingga benda tersebut benar-benar berada di atas tanah.', 'Ingat 地下, yang artinya "di bawah tanah". Nah, ini adalah gabungan antara tanah dan di atas, jadi saya yakin Anda bisa menebak bahwa ini berarti di atas tanah. Namun biasanya benda yang berada di atas tanah tidak mengapung (kecuali jika berada di luar angkasa), sehingga benda tersebut benar-benar berada di atas tanah.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('caa109d7-57f0-444f-b173-30cfea742a26', 'Di Atas Tanah', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('caa109d7-57f0-444f-b173-30cfea742a26', 'On The Ground', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('caa109d7-57f0-444f-b173-30cfea742a26', 'ちじょう', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('caa109d7-57f0-444f-b173-30cfea742a26', ' 木のはが地上におちた。', 'Daunnya jatuh ke tanah.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('caa109d7-57f0-444f-b173-30cfea742a26', 'コウイチは地上1kmの所に、ひみつき地をもっている。', 'Koichi memiliki Pangkalan Rahasia 1 km di atas tanah.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('caa109d7-57f0-444f-b173-30cfea742a26', '東京タワーは、地上から見上げると物凄い迫力がありますね。', 'Saat Anda melihat Menara Tokyo dari bawah, rasanya luar biasa dahsyatnya.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('b4ee7a19-cd26-4647-811c-a32ab65d1285', 'vocabulary', '足す', '足す', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Ingat 足りる? Itu berarti "menjadi cukup". Bagaimana Anda bisa membuat sesuatu menjadi cukup? Anda terus menambahkan sesuatu ke tumpukan sampai Anda mencapai titik di mana jumlahnya cukup! Itu sebabnya kata kerjanya adalah menambahkan sesuatu, karena Anda terus menambahkan sesuatu sampai Anda 足りる.

Kata kerja ini bersifat transitif, seperti kebanyakan kata kerja yang berakhiran す, itulah sebabnya Anda menambahkan sesuatu. Itu tidak bertambah dengan sendirinya. Mungkin Anda menambahkan terlalu banyak sehingga seseorang mencoba menuntut (す) Anda atas tumpukan tupai jahat yang Anda simpan di luar.', 'Ingat 足りる? Itu berarti "menjadi cukup". Bagaimana Anda bisa membuat sesuatu menjadi cukup? Anda terus menambahkan sesuatu ke tumpukan sampai Anda mencapai titik di mana jumlahnya cukup! Itu sebabnya kata kerjanya adalah menambahkan sesuatu, karena Anda terus menambahkan sesuatu sampai Anda 足りる.

Kata kerja ini bersifat transitif, seperti kebanyakan kata kerja yang berakhiran す, itulah sebabnya Anda menambahkan sesuatu. Itu tidak bertambah dengan sendirinya. Mungkin Anda menambahkan terlalu banyak sehingga seseorang mencoba menuntut (す) Anda atas tumpukan tupai jahat yang Anda simpan di luar.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('b4ee7a19-cd26-4647-811c-a32ab65d1285', 'Untuk Menambahkan Sesuatu', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('b4ee7a19-cd26-4647-811c-a32ab65d1285', 'たす', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('b4ee7a19-cd26-4647-811c-a32ab65d1285', '三足す二は五です。', 'Tiga tambah dua adalah lima.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('b4ee7a19-cd26-4647-811c-a32ab65d1285', 'このスープ、もう少し水を足した方がいいんじゃないかな。', 'Mungkin lebih baik menambahkan lebih banyak air ke dalam sup ini.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('b4ee7a19-cd26-4647-811c-a32ab65d1285', 'ここにもう少し文章を書き足すことはできますか？', 'Bisakah Anda menambahkan sedikit lagi pada kalimat ini di sini?') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'vocabulary', '別れる', '別れる', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Karena hiragana diakhiri dengan bunyi う, Anda tahu kata ini adalah kata kerja. Kanjinya sendiri artinya terpisah, jadi bisa ditebak maksudnya memisahkan atau membagi.', 'Karena hiragana diakhiri dengan bunyi う, Anda tahu kata ini adalah kata kerja. Kanjinya sendiri artinya terpisah, jadi bisa ditebak maksudnya memisahkan atau membagi.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'Untuk Memisahkan', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'To Be Divided', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'To Part From', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'To Break Up', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'わかれる', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'コウイチ子はコウイチと別れてビエトと付き合いました。', 'Koichiko berpisah dari Koichi dan mulai berkencan dengan Viet.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', 'コミュニケーション不足がげんいんで別れました。', 'Kami putus karena kurangnya komunikasi.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('6a3dae58-c6b3-4a92-9227-c20dd69509b0', '彼女と別れる時に、涙が止まらなかった。', 'Ketika saya berpisah darinya, saya tidak bisa berhenti menangis.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'vocabulary', '会', '会', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Ini adalah versi kata benda dari pertemuan kanji. Jadi itu berarti pertemuan.', 'Ini adalah versi kata benda dari pertemuan kanji. Jadi itu berarti pertemuan.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'Rapat', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'Assembly', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'Party', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'かい', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'きんようびの夜に、女子会をします。', 'Saya mengadakan pesta khusus perempuan pada Jumat malam.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'そのメンバーの会はとてもおも白そうですね。', 'Pertemuan dengan para anggota tersebut terdengar sangat menarik.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('0223917c-3053-4d36-a0a9-6602c54ca12a', 'この会、また開こうよ！', 'Mari kita buka pertemuan ini lagi!') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'vocabulary', '早く', '早く', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Ini adalah versi kata keterangan dari kanji awal. Ini adalah hal kecil yang dapat Anda gunakan untuk memulai kalimat yang mengatakan Anda melakukan sesuatu lebih awal atau cepat.', 'Ini adalah versi kata keterangan dari kanji awal. Ini adalah hal kecil yang dapat Anda gunakan untuk memulai kalimat yang mengatakan Anda melakukan sesuatu lebih awal atau cepat.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'Awal', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'Soon', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'Quickly', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'Fast', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'はやく', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'きのうはどうして早く学校に行きましたか。', 'Mengapa kamu pergi ke sekolah lebih awal kemarin?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', 'ゆっくり休んで早くよくなってください。', 'Silakan banyak istirahat dan segera merasa lebih baik!') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('2f89818d-c3f8-4681-91c1-7630d30f187f', '早く食べなさい。', 'Makan dengan cepat.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('94ab5021-cb31-4615-8501-79221179f936', 'vocabulary', '死', '死', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Kanji dan kata-katanya sama persis. Itu berarti mereka juga berbagi makna.', 'Kanji dan kata-katanya sama persis. Itu berarti mereka juga berbagi makna.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('94ab5021-cb31-4615-8501-79221179f936', 'Kematian', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('94ab5021-cb31-4615-8501-79221179f936', 'し', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('94ab5021-cb31-4615-8501-79221179f936', 'その死は早すぎました。', 'Kematian mereka terlalu cepat.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('94ab5021-cb31-4615-8501-79221179f936', '人は死をのがれることはできない…コウイチい外は。', 'Orang tidak bisa lepas dari kematian, kecuali Koichi.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('94ab5021-cb31-4615-8501-79221179f936', '愛犬の死に打ちひしがれています。', 'Saya dilanda kesedihan atas kematian anjing peliharaan saya.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'vocabulary', '近く', '近く', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Ini adalah versi kata benda dari kanji dekat. Jadi itu juga berarti dekat, atau di sekitar sesuatu.', 'Ini adalah versi kata benda dari kanji dekat. Jadi itu juga berarti dekat, atau di sekitar sesuatu.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'Dekat', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'Neighborhood', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'Vicinity', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'Nearly', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'Shortly', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'ちかく', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', '今は、学校の近くに、姉とすんでいます。', 'Saat ini saya tinggal bersama saudara perempuan saya di dekat sekolah.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', 'あのアイドル、近くで見るとあんまりかわいくないね。', 'Kalau dilihat dari dekat, idola remaja itu nggak cantik sama sekali ya?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('2590b80a-5e45-4acf-893f-ce6d2b902f5e', '近くの焼き鳥屋で、一杯ひっかけていかないか。', 'Tidakkah Anda ingin minum di toko yakitori terdekat?') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('5ab43d6a-477e-468c-88ff-d4104450be8c', 'vocabulary', '考古学', '考古学', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Kalau sering terpikir untuk mempelajari benda-benda kuno, namanya arkeologi. Semua arkeologi melibatkan pemikiran tentang hal-hal lama, setidaknya sedikit.', 'Kalau sering terpikir untuk mempelajari benda-benda kuno, namanya arkeologi. Semua arkeologi melibatkan pemikiran tentang hal-hal lama, setidaknya sedikit.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('5ab43d6a-477e-468c-88ff-d4104450be8c', 'Arkeologi', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('5ab43d6a-477e-468c-88ff-d4104450be8c', 'Archaeology', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('5ab43d6a-477e-468c-88ff-d4104450be8c', 'こうこがく', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5ab43d6a-477e-468c-88ff-d4104450be8c', 'わたしは、日本の考古学にきょうみがあります。', 'Saya tertarik dengan arkeologi Jepang.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5ab43d6a-477e-468c-88ff-d4104450be8c', '今月末でこの考古学のしごとをやめるんです。', 'Saya akan berhenti dari pekerjaan arkeologi ini pada akhir bulan.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('5ab43d6a-477e-468c-88ff-d4104450be8c', 'この大学では、考古学を学べます。', 'Anda dapat belajar arkeologi di universitas ini.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('d716860b-fb39-47cc-a0aa-f6456a294cc4', 'vocabulary', '地中', '地中', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Jika Anda berada di tengah tanah, kemungkinan besar Anda berada di bawah tanah. Apakah Anda seorang penganiaya? Itu cukup keren.', 'Jika Anda berada di tengah tanah, kemungkinan besar Anda berada di bawah tanah. Apakah Anda seorang penganiaya? Itu cukup keren.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('d716860b-fb39-47cc-a0aa-f6456a294cc4', 'Bawah Tanah', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('d716860b-fb39-47cc-a0aa-f6456a294cc4', 'Subterranean', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('d716860b-fb39-47cc-a0aa-f6456a294cc4', 'ちちゅう', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('d716860b-fb39-47cc-a0aa-f6456a294cc4', '地中は、冬にはあたたかく、なつはつめたいです。', 'Di bawah tanah hangat di musim dingin dan dingin di musim panas.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('d716860b-fb39-47cc-a0aa-f6456a294cc4', '多くのみずうみは、地中の水ろでつながっています。', 'Banyak danau yang dihubungkan oleh saluran bawah tanah.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('d716860b-fb39-47cc-a0aa-f6456a294cc4', '地中の温度を測るにはどうすればいいですか。', 'Apa yang harus saya lakukan untuk mengukur suhu di bawah tanah?') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', 'vocabulary', '一体', '一体', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Oke, jadi yang ini aneh sekali, maaf. Masing-masing dari kita hanya mendapatkan satu tubuh seumur hidup, bukan? Ya, apa-apaan ini! Bagaimana jika saya menginginkan lebih dari satu tubuh. Mari kita semua marah tentang hal ini bersama-sama.', 'Oke, jadi yang ini aneh sekali, maaf. Masing-masing dari kita hanya mendapatkan satu tubuh seumur hidup, bukan? Ya, apa-apaan ini! Bagaimana jika saya menginginkan lebih dari satu tubuh. Mari kita semua marah tentang hal ini bersama-sama.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', 'Persetan', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', 'In The World', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', 'On Earth', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', 'いったい', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', '一体どうなっているんだ。', 'Apa yang sedang terjadi?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', '「あいとにくしみはひょうり一体」って、一体全体どういういみなんだ！？', 'Apa maksudnya, "Ada garis tipis antara cinta dan benci"?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('12c37eb5-cf5e-489b-9f33-10cf06b3fe8e', '一体俺が何をしたって言うんだよ？', 'Apa yang kamu bilang aku lakukan?') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'vocabulary', '生地', '生地', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Kehidupan yang keluar dari bumi terdiri dari berbagai jenis bahan. Kadang kain, kadang adonan, tapi semuanya harus terbuat dari sesuatu.', 'Kehidupan yang keluar dari bumi terdiri dari berbagai jenis bahan. Kadang kain, kadang adonan, tapi semuanya harus terbuat dari sesuatu.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'Bahan', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'Cloth', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'Fabric', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'Dough', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'Batter', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'きじ', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'マリメッコの生地でクッションを作りました。', 'Saya membuat bantal dari kain Marimekko.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', 'このカーテンは、パラシュート生地でできています。', 'Tirai ini terbuat dari bahan parasut.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('4ca81e1b-35e3-4dd0-a682-0182dd927933', '冷凍のパイ生地を買ってきてください。', 'Silakan beli potongan beku.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('39832552-1b81-4155-8aea-0c5ae3a308b7', 'vocabulary', '別', '別', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Kanji dan kata-katanya sama persis. Itu berarti mereka juga berbagi makna.', 'Kanji dan kata-katanya sama persis. Itu berarti mereka juga berbagi makna.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('39832552-1b81-4155-8aea-0c5ae3a308b7', 'Berbeda', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('39832552-1b81-4155-8aea-0c5ae3a308b7', 'Separate', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('39832552-1b81-4155-8aea-0c5ae3a308b7', 'べつ', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('39832552-1b81-4155-8aea-0c5ae3a308b7', 'コウイチが、別の女と歩いているところを見たの。', 'Saya melihat Koichi berjalan dengan gadis yang berbeda.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('39832552-1b81-4155-8aea-0c5ae3a308b7', 'それとこれとは話が別だろう。', 'Ini dan itu adalah dua cerita yang berbeda.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('39832552-1b81-4155-8aea-0c5ae3a308b7', 'その場合は別として、このやり方で男女を別にするのは通じょうもんだいありません。', 'Selain itu, biasanya tidak masalah jika memisahkan jenis kelamin dengan cara ini.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', 'vocabulary', '大体', '大体', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Jika yang Anda lihat hanyalah bagian besar dari suatu benda, maka Anda hanya akan mendapatkan gambaran umum tentang benda tersebut. Anda akan dapat mengatakan bahwa secara umum ini adalah cara tertentu, tetapi itu saja. Anda akan mendapatkan intinya, tapi tidak lebih.', 'Jika yang Anda lihat hanyalah bagian besar dari suatu benda, maka Anda hanya akan mendapatkan gambaran umum tentang benda tersebut. Anda akan dapat mengatakan bahwa secara umum ini adalah cara tertentu, tetapi itu saja. Anda akan mendapatkan intinya, tapi tidak lebih.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', 'Umumnya', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', 'About', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', 'General', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', 'Gist', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', 'だいたい', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', '大体あっています。', 'Itu benar.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', '大体同じぐらいのせです。', 'Tinggi badan kami hampir sama.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('e5869fca-50d9-4494-b10b-752becd8fe9c', '私は大体6時に起きます。', 'Saya biasanya bangun jam 6 sore.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', 'vocabulary', '広げる', '広げる', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Kata ini terdiri dari kanji dengan hiragana ditempelkan. Karena hiragana diakhiri dengan bunyi う, Anda tahu kata ini adalah kata kerja. 

Kanjinya sendiri artinya lebar, dan versi kata kerjanya adalah apa yang terjadi ketika Anda mencoba membuat sesuatu lebih luas. Bagaimana cara membuat sesuatu lebih luas? Benar sekali, Anda harus menyebarkan sesuatu, membuka sesuatu, atau membuka sesuatu. Semua tindakan itu akan membuat segalanya menjadi lebih luas!

Ini adalah kata kerja transitif. Artinya dibutuhkan objek langsung. Anda menyebarkan sesuatu. Seperti koran, atau kain di atas meja.', 'Kata ini terdiri dari kanji dengan hiragana ditempelkan. Karena hiragana diakhiri dengan bunyi う, Anda tahu kata ini adalah kata kerja. 

Kanjinya sendiri artinya lebar, dan versi kata kerjanya adalah apa yang terjadi ketika Anda mencoba membuat sesuatu lebih luas. Bagaimana cara membuat sesuatu lebih luas? Benar sekali, Anda harus menyebarkan sesuatu, membuka sesuatu, atau membuka sesuatu. Semua tindakan itu akan membuat segalanya menjadi lebih luas!

Ini adalah kata kerja transitif. Artinya dibutuhkan objek langsung. Anda menyebarkan sesuatu. Seperti koran, atau kain di atas meja.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', 'Untuk Menyebarkan Sesuatu', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', 'To Unfold Something', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', 'To Open Something Up', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', 'ひろげる', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', '日本にそのウィルスを広げたのは水だった。', 'Airlah yang menyebarkan virus di Jepang.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', '大人三人でブランケットを広げた。', 'Tiga orang dewasa membuka selimut.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('25395bac-b32f-4415-8f6f-28afbcbd874d', '中に入ってすぐ本を広げた。', 'Segera setelah saya masuk ke dalam, saya membuka buku itu.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', 'vocabulary', '出身', '出身', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Jalan keluar seseorang memulai adalah asal usulnya, kampung halamannya, atau tempat kelahirannya.', 'Jalan keluar seseorang memulai adalah asal usulnya, kampung halamannya, atau tempat kelahirannya.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', 'Asal Usul Seseorang', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', 'One''s Hometown', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', 'One''s Birthplace', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', 'しゅっしん', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', 'どこの出身ですか。', 'Asalmu dari mana?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', '私たちは二人とも中国出身です。', 'Kami berdua berasal dari Tiongkok.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('a1510bc1-9149-488d-97eb-4bda5b6f306a', '夕べのパーティーに、同じ出身の人がいました。', 'Di pesta tadi malam, ada seseorang dari kampung halamanku.') ON CONFLICT DO NOTHING;
INSERT INTO public.items (id, type, character, slug, level, rank_id, meaning_mnemonic, description) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', 'vocabulary', '出社', '出社', 2, 'e5f6a7b8-c90d-1e2f-3a4b-5c6d7e8f9a0b', 'Jika Anda keluar dari suatu tempat untuk pergi ke perusahaan Anda, itu pergi ke kantor, tiba di kantor, dan berangkat kerja.', 'Jika Anda keluar dari suatu tempat untuk pergi ke perusahaan Anda, itu pergi ke kantor, tiba di kantor, dan berangkat kerja.') ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, character = EXCLUDED.character, slug = EXCLUDED.slug, level = EXCLUDED.level, rank_id = EXCLUDED.rank_id, meaning_mnemonic = EXCLUDED.meaning_mnemonic, description = EXCLUDED.description;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', 'Pergi Ke Kantor', true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', 'Arriving At The Office', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_meanings (item_id, meaning, primary_meaning) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', 'Coming To Work', false) ON CONFLICT DO NOTHING;
INSERT INTO public.item_readings (item_id, reading, reading_type, primary_reading) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', 'しゅっしゃ', NULL, true) ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', '今日は、八時に出社しました。', 'Hari ini saya tiba di kantor jam 8 malam.') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', '出社前って、どんな風にすごしてますか？', 'Bagaimana Anda menghabiskan waktu sebelum berangkat kerja?') ON CONFLICT DO NOTHING;
INSERT INTO public.item_context_sentences (item_id, japanese, indonesian) VALUES ('fa893367-17ae-4940-b7f8-fd600a688f92', 'もう出社しているはずなのに。', 'Tapi mereka seharusnya sudah bekerja sekarang.') ON CONFLICT DO NOTHING;

-- 5. Insert Kanji-to-Radical Prerequisites
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '205feb54-24cb-4604-8d4d-5e752f320441', id FROM public.items WHERE type = 'radical' AND slug = 'dirt' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '205feb54-24cb-4604-8d4d-5e752f320441', id FROM public.items WHERE type = 'radical' AND slug = 'dirt' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '205feb54-24cb-4604-8d4d-5e752f320441', id FROM public.items WHERE type = 'radical' AND slug = 'private' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '205feb54-24cb-4604-8d4d-5e752f320441', id FROM public.items WHERE type = 'radical' AND slug = 'private' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '8876edc5-41bb-4478-9fd9-9ab384f7deb2', id FROM public.items WHERE type = 'radical' AND slug = 'canopy' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '8876edc5-41bb-4478-9fd9-9ab384f7deb2', id FROM public.items WHERE type = 'radical' AND slug = 'canopy' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '8876edc5-41bb-4478-9fd9-9ab384f7deb2', id FROM public.items WHERE type = 'radical' AND slug = 'private' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '8876edc5-41bb-4478-9fd9-9ab384f7deb2', id FROM public.items WHERE type = 'radical' AND slug = 'private' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'f88dfc1a-284f-4117-8d5d-8bff7bb46e15', id FROM public.items WHERE type = 'radical' AND slug = 'forehead' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'f88dfc1a-284f-4117-8d5d-8bff7bb46e15', id FROM public.items WHERE type = 'radical' AND slug = 'forehead' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'f88dfc1a-284f-4117-8d5d-8bff7bb46e15', id FROM public.items WHERE type = 'radical' AND slug = 'ground' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'f88dfc1a-284f-4117-8d5d-8bff7bb46e15', id FROM public.items WHERE type = 'radical' AND slug = 'ground' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'f88dfc1a-284f-4117-8d5d-8bff7bb46e15', id FROM public.items WHERE type = 'radical' AND slug = 'beggar' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'f88dfc1a-284f-4117-8d5d-8bff7bb46e15', id FROM public.items WHERE type = 'radical' AND slug = 'beggar' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'be7b7c13-8c99-45ed-ac0a-632e895a9a01', id FROM public.items WHERE type = 'radical' AND slug = 'old' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'be7b7c13-8c99-45ed-ac0a-632e895a9a01', id FROM public.items WHERE type = 'radical' AND slug = 'old' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '72d9015a-283b-4ede-a2f4-afd65001dc7f', id FROM public.items WHERE type = 'radical' AND slug = 'mouth' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '72d9015a-283b-4ede-a2f4-afd65001dc7f', id FROM public.items WHERE type = 'radical' AND slug = 'mouth' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '72d9015a-283b-4ede-a2f4-afd65001dc7f', id FROM public.items WHERE type = 'radical' AND slug = 'legs' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '72d9015a-283b-4ede-a2f4-afd65001dc7f', id FROM public.items WHERE type = 'radical' AND slug = 'legs' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '65c6851b-7081-47a0-8059-ee9618433ee9', id FROM public.items WHERE type = 'radical' AND slug = 'winter' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '65c6851b-7081-47a0-8059-ee9618433ee9', id FROM public.items WHERE type = 'radical' AND slug = 'winter' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '65c6851b-7081-47a0-8059-ee9618433ee9', id FROM public.items WHERE type = 'radical' AND slug = 'two' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '65c6851b-7081-47a0-8059-ee9618433ee9', id FROM public.items WHERE type = 'radical' AND slug = 'two' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '4bf9164a-ae65-41fb-95bc-0f16d486acbc', id FROM public.items WHERE type = 'radical' AND slug = 'meet' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '4bf9164a-ae65-41fb-95bc-0f16d486acbc', id FROM public.items WHERE type = 'radical' AND slug = 'meet' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'dc496f9c-c6b3-4a1e-ba63-d85f90766283', id FROM public.items WHERE type = 'radical' AND slug = 'self' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'dc496f9c-c6b3-4a1e-ba63-d85f90766283', id FROM public.items WHERE type = 'radical' AND slug = 'self' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '5c4c770c-f9e7-49be-8bcf-d718aff12ec9', id FROM public.items WHERE type = 'radical' AND slug = 'mustache' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '5c4c770c-f9e7-49be-8bcf-d718aff12ec9', id FROM public.items WHERE type = 'radical' AND slug = 'mustache' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '5c4c770c-f9e7-49be-8bcf-d718aff12ec9', id FROM public.items WHERE type = 'radical' AND slug = 'ground' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '5c4c770c-f9e7-49be-8bcf-d718aff12ec9', id FROM public.items WHERE type = 'radical' AND slug = 'ground' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'e1cb826f-3d14-45b1-a3ed-b16dadf4d973', id FROM public.items WHERE type = 'radical' AND slug = 'dirt' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'e1cb826f-3d14-45b1-a3ed-b16dadf4d973', id FROM public.items WHERE type = 'radical' AND slug = 'dirt' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'e1cb826f-3d14-45b1-a3ed-b16dadf4d973', id FROM public.items WHERE type = 'radical' AND slug = 'alligator' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'e1cb826f-3d14-45b1-a3ed-b16dadf4d973', id FROM public.items WHERE type = 'radical' AND slug = 'alligator' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'b12d5793-c36b-4cf6-9a4f-bffb6a15f557', id FROM public.items WHERE type = 'radical' AND slug = 'yakuza' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'b12d5793-c36b-4cf6-9a4f-bffb6a15f557', id FROM public.items WHERE type = 'radical' AND slug = 'yakuza' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'b12d5793-c36b-4cf6-9a4f-bffb6a15f557', id FROM public.items WHERE type = 'radical' AND slug = 'spoon' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'b12d5793-c36b-4cf6-9a4f-bffb6a15f557', id FROM public.items WHERE type = 'radical' AND slug = 'spoon' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '971e847f-cb01-45cf-b0a1-16b67338d6e5', id FROM public.items WHERE type = 'radical' AND slug = 'coffin' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '971e847f-cb01-45cf-b0a1-16b67338d6e5', id FROM public.items WHERE type = 'radical' AND slug = 'coffin' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '971e847f-cb01-45cf-b0a1-16b67338d6e5', id FROM public.items WHERE type = 'radical' AND slug = 'beggar' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '971e847f-cb01-45cf-b0a1-16b67338d6e5', id FROM public.items WHERE type = 'radical' AND slug = 'beggar' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'd935e776-2ce1-41cd-b0e3-77f4e0b9693b', id FROM public.items WHERE type = 'radical' AND slug = 'roof' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'd935e776-2ce1-41cd-b0e3-77f4e0b9693b', id FROM public.items WHERE type = 'radical' AND slug = 'roof' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT 'd935e776-2ce1-41cd-b0e3-77f4e0b9693b', id FROM public.items WHERE type = 'radical' AND slug = 'woman' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT 'd935e776-2ce1-41cd-b0e3-77f4e0b9693b', id FROM public.items WHERE type = 'radical' AND slug = 'woman' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '0f457b18-22e5-4fde-a772-cb6efe5b2f7a', id FROM public.items WHERE type = 'radical' AND slug = 'evening' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '0f457b18-22e5-4fde-a772-cb6efe5b2f7a', id FROM public.items WHERE type = 'radical' AND slug = 'evening' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '69c8b732-e0ca-4c50-beed-271ae9beaf8b', id FROM public.items WHERE type = 'radical' AND slug = 'sun' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '69c8b732-e0ca-4c50-beed-271ae9beaf8b', id FROM public.items WHERE type = 'radical' AND slug = 'sun' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '69c8b732-e0ca-4c50-beed-271ae9beaf8b', id FROM public.items WHERE type = 'radical' AND slug = 'cross' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '69c8b732-e0ca-4c50-beed-271ae9beaf8b', id FROM public.items WHERE type = 'radical' AND slug = 'cross' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '69e2c7c0-fadb-4b39-a3e5-5ee09cf529da', id FROM public.items WHERE type = 'radical' AND slug = 'narwhal' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.kanji_radicals (kanji_id, radical_id)
SELECT '69e2c7c0-fadb-4b39-a3e5-5ee09cf529da', id FROM public.items WHERE type = 'radical' AND slug = 'narwhal' LIMIT 1 ON CONFLICT DO NOTHING;
INSERT INTO public.item_prerequisites (item_id, requires_item_id)
SELECT '69e2c7c0-fadb-4b39-a3e5-5ee09cf529da', id FROM public.items WHERE type = 'radical' AND slug = 'moon' LIMIT 1 ON CONFLICT DO NOTHING;